In [31]:
import pandas as pd

df = pd.read_csv('dataset\sentiment-analysis.csv')

In [32]:
df

,Text,Sentiment,Source,Date/Time,User ID,Location,Confidence Score
0,"I love this product!""""",Positive,Twitter,2023-06-15 09:23:14,@user123,New York,0.85
1,"The service was terrible.""""",Negative,Yelp Reviews,2023-06-15 11:45:32,user456,Los Angeles,0.65
2,"This movie is amazing!""""",Positive,IMDb,2023-06-15 14:10:22,moviefan789,London,0.92
3,I'm so disappointed with their customer suppor...,Negative,Online Forum,2023-06-15 17:35:11,forumuser1,Toronto,0.78
4,"Terribly disappointed with the service, wouldn...",Negative,Product Feedback,2023-12-26 20:24:04,daenskawzp,New York,0.53
...,...,...,...,...,...,...,...
95,Their website is so confusing and poorly desig...,Negative,Website Review,2023-07-03 11:59:18,user789,Toronto,"0.68"""
96,I had an incredible experience at the theme pa...,Positive,Trip Report,2023-07-03 14:40:05,thrillseeker1,Orlando,"0.89"""
97,"Horrible experience, would not recommend to an...",Negative,Trip Report,2024-03-19 02:58:44,ecyscfhngd,New York,0.55
98,"The product quality was bad, completely unsati...",Negative,Product Feedback,2024-02-01 16:20:05,wsweeriejy,Toronto,0.59
99,Unfriendly staff and bad customer service. Bad,Negative,Trip Report,2024-02-03 22:59:22,lxpswqdlzj,New York,0.53

In [33]:
df["Text"] = df["Text"].apply(lambda x: x.rstrip('"'))

In [34]:
df[" Confidence Score"] = df[" Confidence Score"].apply(lambda x: float(str(x).rstrip('"')))

In [35]:
df

,Text,Sentiment,Source,Date/Time,User ID,Location,Confidence Score
0,I love this product!,Positive,Twitter,2023-06-15 09:23:14,@user123,New York,0.85
1,The service was terrible.,Negative,Yelp Reviews,2023-06-15 11:45:32,user456,Los Angeles,0.65
2,This movie is amazing!,Positive,IMDb,2023-06-15 14:10:22,moviefan789,London,0.92
3,I'm so disappointed with their customer support.,Negative,Online Forum,2023-06-15 17:35:11,forumuser1,Toronto,0.78
4,"Terribly disappointed with the service, wouldn...",Negative,Product Feedback,2023-12-26 20:24:04,daenskawzp,New York,0.53
...,...,...,...,...,...,...,...
95,Their website is so confusing and poorly desig...,Negative,Website Review,2023-07-03 11:59:18,user789,Toronto,0.68
96,I had an incredible experience at the theme pa...,Positive,Trip Report,2023-07-03 14:40:05,thrillseeker1,Orlando,0.89
97,"Horrible experience, would not recommend to an...",Negative,Trip Report,2024-03-19 02:58:44,ecyscfhngd,New York,0.55
98,"The product quality was bad, completely unsati...",Negative,Product Feedback,2024-02-01 16:20:05,wsweeriejy,Toronto,0.59
99,Unfriendly staff and bad customer service. Bad,Negative,Trip Report,2024-02-03 22:59:22,lxpswqdlzj,New York,0.53

In [7]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import string

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to C:\Users\Nikhil
[nltk_data]     Pal\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Nikhil
[nltk_data]     Pal\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Nikhil
[nltk_data]     Pal\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [8]:
def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    # Tokenize
    tokens = nltk.word_tokenize(text)
    print(tokens)
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    filtered_tokens = [w for w in tokens if not w in stop_words]
    # Lemmatize
    lemmatizer = WordNetLemmatizer()
    lemmatized_tokens = [lemmatizer.lemmatize(w) for w in filtered_tokens]
    return " ".join(lemmatized_tokens)

In [36]:
df.rename(columns={" Confidence Score": "confidence_score"}, inplace=True)

In [37]:
df

,Text,Sentiment,Source,Date/Time,User ID,Location,confidence_score
0,I love this product!,Positive,Twitter,2023-06-15 09:23:14,@user123,New York,0.85
1,The service was terrible.,Negative,Yelp Reviews,2023-06-15 11:45:32,user456,Los Angeles,0.65
2,This movie is amazing!,Positive,IMDb,2023-06-15 14:10:22,moviefan789,London,0.92
3,I'm so disappointed with their customer support.,Negative,Online Forum,2023-06-15 17:35:11,forumuser1,Toronto,0.78
4,"Terribly disappointed with the service, wouldn...",Negative,Product Feedback,2023-12-26 20:24:04,daenskawzp,New York,0.53
...,...,...,...,...,...,...,...
95,Their website is so confusing and poorly desig...,Negative,Website Review,2023-07-03 11:59:18,user789,Toronto,0.68
96,I had an incredible experience at the theme pa...,Positive,Trip Report,2023-07-03 14:40:05,thrillseeker1,Orlando,0.89
97,"Horrible experience, would not recommend to an...",Negative,Trip Report,2024-03-19 02:58:44,ecyscfhngd,New York,0.55
98,"The product quality was bad, completely unsati...",Negative,Product Feedback,2024-02-01 16:20:05,wsweeriejy,Toronto,0.59
99,Unfriendly staff and bad customer service. Bad,Negative,Trip Report,2024-02-03 22:59:22,lxpswqdlzj,New York,0.53

In [38]:
df["Text"] = df["Text"].apply(preprocess_text)

['i', 'love', 'this', 'product']
['the', 'service', 'was', 'terrible']
['this', 'movie', 'is', 'amazing']
['im', 'so', 'disappointed', 'with', 'their', 'customer', 'support']
['terribly', 'disappointed', 'with', 'the', 'service', 'wouldnt', 'go', 'back', 'bad']
['just', 'had', 'the', 'best', 'meal', 'of', 'my', 'life']
['the', 'quality', 'of', 'this', 'product', 'is', 'subpar']
['i', 'cant', 'stop', 'listening', 'to', 'this', 'song', 'its', 'incredible']
['their', 'website', 'is', 'so', 'userfriendly', 'love', 'it']
['i', 'loved', 'the', 'movie', 'it', 'was', 'fantastic']
['the', 'customer', 'service', 'was', 'terrible']
['this', 'book', 'made', 'me', 'feel', 'inspired', 'highly', 'recommended']
['im', 'extremely', 'disappointed', 'with', 'their', 'product', 'quality']
['just', 'had', 'the', 'most', 'amazing', 'vacation', 'i', 'cant', 'wait', 'to', 'go', 'back']
['the', 'food', 'at', 'this', 'restaurant', 'was', 'awful', 'never', 'going', 'back', 'again']
['i', 'cant', 'stop', 'listening', 'to', 'this', 'song', 'its', 'my', 'new', 'favorite']
['their', 'website', 'is', 'so', 'confusing', 'and', 'poorly', 'designed']
['i', 'had', 'an', 'incredible', 'experience', 'at', 'the', 'theme', 'park', 'so', 'much', 'fun']
['the', 'product', 'arrived', 'damaged', 'very', 'disappointed']
['the', 'concert', 'was', 'absolutely', 'breathtaking', 'best', 'performance', 'ever']
['i', 'had', 'a', 'terrible', 'experience', 'with', 'their', 'customer', 'support']
['this', 'movie', 'is', 'a', 'masterpiece', 'i', 'was', 'blown', 'away']
['the', 'customer', 'service', 'at', 'this', 'store', 'is', 'topnotch']
['im', 'disappointed', 'with', 'the', 'ending', 'of', 'this', 'book', 'it', 'fell', 'flat']
['the', 'product', 'i', 'received', 'was', 'damaged', 'unacceptable']
['just', 'had', 'the', 'worst', 'flight', 'experience', 'delayed', 'and', 'rude', 'staff']
['the', 'hotel', 'stay', 'was', 'absolutely', 'amazing', 'luxury', 'at', 'its', 'finest']
['the', 'food', 'at', 'this', 'restaurant', 'was', 'outstanding', 'highly', 'recommended']
['this', 'playlist', 'is', 'my', 'goto', 'for', 'workouts', 'energizing', 'and', 'motivating']
['i', 'had', 'a', 'frustrating', 'experience', 'navigating', 'through', 'their', 'website']
['the', 'roller', 'coaster', 'ride', 'was', 'thrilling', 'heartpounding', 'excitement']
['the', 'product', 'i', 'ordered', 'never', 'arrived', 'terrible', 'service']
['i', 'cant', 'get', 'enough', 'of', 'this', 'band', 'their', 'music', 'is', 'incredible']
['i', 'had', 'a', 'great', 'chat', 'with', 'their', 'customer', 'support', 'helpful', 'and', 'friendly']
['this', 'restaurant', 'has', 'the', 'most', 'delicious', 'food', 'i', 'cant', 'wait', 'to', 'go', 'back']
['the', 'product', 'i', 'purchased', 'broke', 'within', 'a', 'week', 'poor', 'quality']
['this', 'book', 'is', 'thoughtprovoking', 'and', 'beautifully', 'written', 'highly', 'recommended']
['the', 'customer', 'service', 'at', 'this', 'store', 'is', 'exceptional', 'they', 'went', 'above', 'and', 'beyond']
['i', 'had', 'a', 'terrible', 'experience', 'with', 'their', 'technical', 'support', 'no', 'resolution']
['the', 'live', 'concert', 'was', 'electrifying', 'the', 'bands', 'energy', 'was', 'contagious']
['im', 'disappointed', 'with', 'the', 'food', 'at', 'this', 'restaurant', 'it', 'was', 'tasteless']
['this', 'song', 'always', 'puts', 'me', 'in', 'a', 'good', 'mood', 'its', 'my', 'goto', 'feelgood', 'track']
['the', 'website', 'is', 'slow', 'and', 'unresponsive', 'difficult', 'to', 'navigate']
['the', 'roller', 'coaster', 'ride', 'was', 'exhilarating', 'pure', 'adrenaline', 'rush']
['the', 'product', 'i', 'ordered', 'arrived', 'damaged', 'very', 'disappointed', 'with', 'the', 'packaging']
['im', 'captivated', 'by', 'this', 'bands', 'unique', 'sound', 'theyre', 'a', 'breath', 'of', 'fresh', 'air']
['the', 'customer', 'support', 'was', 'quick', 'to', 'respond', 'and', 'resolved', 'my', 'issue', 'impressed']
['this', 'restaurant', 'has', 'the', 'best', 'food', 'i', 'highly', 'recommend', 'it']
['the', 'plot', 'of', 'this', 'movie', 'is', 'confusing', 'and', 'hard', 'to', 'follow']
['im', 'addicted', 'to', 'this', 'game', 'its', 'so', 'much', 'fun']
['the', 'customer', 'service', 'at', 'this', 'hotel', 'was', 'terrible', 'avoid', 'at', 'all', 'costs']
['this', 'book', 'bored', 'me', 'to', 'tears', 'i', 'couldnt', 'finish', 'it']
['im', 'impressed', 'with', 'the', 'sound', 'quality', 'of', 'these', 'headphones', 'excellent']
['the', 'website', 'design', 'is', 'sleek', 'and', 'userfriendly', 'easy', 'to', 'navigate']
['i', 'had', 'a', 'terrible', 'experience', 'with', 'their', 'delivery', 'service', 'late', 'and', 'unprofessional']
['the', 'concert', 'was', 'mindblowing', 'the', 'band', 'knows', 'how', 'to', 'put', 'on', 'a', 'show']
['im', 'extremely', 'disappointed', 'with', 'the', 'customer', 'support', 'no', 'resolution']
['the', 'hotel', 'staff', 'were', 'rude', 'and', 'unprofessional', 'terrible', 'customer', 'service']
['the', 'food', 'at', 'this', 'restaurant', 'was', 'mediocre', 'nothing', 'special']
['this', 'song', 'always', 'puts', 'me', 'in', 'a', 'nostalgic', 'mood', 'it', 'reminds', 'me', 'of', 'good', 'times', 'positive', 'spotify', '20230717', '142005', 'nostalgiacat123', 'berlin', '088']
['the', 'website', 'loading', 'speed', 'is', 'frustratingly', 'slow', 'needs', 'improvement']
['the', 'food', 'at', 'this', 'cafe', 'exceeded', 'my', 'expectations', 'absolutely', 'delicious']
['im', 'disappointed', 'with', 'the', 'ending', 'of', 'this', 'tv', 'show', 'it', 'left', 'too', 'many', 'unanswered', 'questions']
['this', 'album', 'is', 'a', 'masterpiece', 'every', 'song', 'is', 'a', 'work', 'of', 'art']
['the', 'website', 'layout', 'is', 'cluttered', 'and', 'confusing', 'difficult', 'to', 'find', 'information']
['the', 'roller', 'coaster', 'at', 'this', 'theme', 'park', 'is', 'a', 'thrilling', 'experience', 'a', 'musttry']
['the', 'product', 'i', 'ordered', 'never', 'arrived', 'poor', 'customer', 'service']
['im', 'in', 'awe', 'of', 'this', 'artists', 'talent', 'their', 'paintings', 'are', 'breathtaking']
['the', 'food', 'at', 'this', 'restaurant', 'was', 'disappointing', 'not', 'worth', 'the', 'price']
['this', 'playlist', 'is', 'perfect', 'for', 'relaxation', 'soothing', 'and', 'calming']
['the', 'website', 'navigation', 'is', 'smooth', 'and', 'intuitive', 'i', 'found', 'what', 'i', 'needed', 'quickly']
['the', 'ride', 'on', 'this', 'cruise', 'ship', 'was', 'an', 'unforgettable', 'experience', 'i', 'loved', 'every', 'moment']
['the', 'product', 'i', 'received', 'was', 'of', 'poor', 'quality', 'it', 'broke', 'after', 'a', 'few', 'uses']
['this', 'book', 'kept', 'me', 'hooked', 'from', 'start', 'to', 'finish', 'a', 'captivating', 'read']
['the', 'customer', 'service', 'at', 'this', 'store', 'is', 'outstanding', 'they', 'truly', 'care', 'about', 'their', 'customers']
['i', 'had', 'a', 'frustrating', 'experience', 'with', 'their', 'technical', 'support', 'no', 'resolution', 'provided']
['the', 'hotel', 'staff', 'were', 'rude', 'and', 'unprofessional', 'terrible', 'customer', 'service']
['the', 'food', 'at', 'this', 'restaurant', 'was', 'mediocre', 'nothing', 'special']
['this', 'song', 'always', 'puts', 'me', 'in', 'a', 'nostalgic', 'mood', 'it', 'reminds', 'me', 'of', 'good', 'times']
['the', 'website', 'loading', 'speed', 'is', 'frustratingly', 'slow', 'needs', 'improvement']
['i', 'love', 'this', 'product']
['the', 'service', 'was', 'terrible']
['this', 'movie', 'is', 'amazing']
['im', 'so', 'disappointed', 'with', 'their', 'customer', 'support']
['just', 'had', 'the', 'best', 'meal', 'of', 'my', 'life']
['the', 'quality', 'of', 'this', 'product', 'is', 'subpar']
['i', 'cant', 'stop', 'listening', 'to', 'this', 'song', 'its', 'incredible']
['their', 'website', 'is', 'so', 'userfriendly', 'love', 'it']
['i', 'loved', 'the', 'movie', 'it', 'was', 'fantastic']
['the', 'customer', 'service', 'was', 'terrible']
['this', 'book', 'made', 'me', 'feel', 'inspired', 'highly', 'recommended']
['im', 'extremely', 'disappointed', 'with', 'their', 'product', 'quality']
['just', 'had', 'the', 'most', 'amazing', 'vacation', 'i', 'cant', 'wait', 'to', 'go', 'back']
['the', 'food', 'at', 'this', 'restaurant', 'was', 'awful', 'never', 'going', 'back', 'again']
['i', 'cant', 'stop', 'listening', 'to', 'this', 'song', 'its', 'my', 'new', 'favorite']
['their', 'website', 'is', 'so', 'confusing', 'and', 'poorly', 'designed']
['i', 'had', 'an', 'incredible', 'experience', 'at', 'the', 'theme', 'park', 'so', 'much', 'fun']
['horrible', 'experience', 'would', 'not', 'recommend', 'to', 'anyone', 'bad']
['the', 'product', 'quality', 'was', 'bad', 'completely', 'unsatisfied', 'bad']
['unfriendly', 'staff', 'and', 'bad', 'customer', 'service', 'bad']

In [39]:
df

,Text,Sentiment,Source,Date/Time,User ID,Location,confidence_score
0,love product,Positive,Twitter,2023-06-15 09:23:14,@user123,New York,0.85
1,service terrible,Negative,Yelp Reviews,2023-06-15 11:45:32,user456,Los Angeles,0.65
2,movie amazing,Positive,IMDb,2023-06-15 14:10:22,moviefan789,London,0.92
3,im disappointed customer support,Negative,Online Forum,2023-06-15 17:35:11,forumuser1,Toronto,0.78
4,terribly disappointed service wouldnt go back bad,Negative,Product Feedback,2023-12-26 20:24:04,daenskawzp,New York,0.53
...,...,...,...,...,...,...,...
95,website confusing poorly designed,Negative,Website Review,2023-07-03 11:59:18,user789,Toronto,0.68
96,incredible experience theme park much fun,Positive,Trip Report,2023-07-03 14:40:05,thrillseeker1,Orlando,0.89
97,horrible experience would recommend anyone bad,Negative,Trip Report,2024-03-19 02:58:44,ecyscfhngd,New York,0.55
98,product quality bad completely unsatisfied bad,Negative,Product Feedback,2024-02-01 16:20:05,wsweeriejy,Toronto,0.59
99,unfriendly staff bad customer service bad,Negative,Trip Report,2024-02-03 22:59:22,lxpswqdlzj,New York,0.53

In [35]:

df.columns

Index(['Text', ' Sentiment', ' Source', ' Date/Time', ' User ID', ' Location',
       'confidence_score'],
      dtype='object')

In [40]:
df["confidence"] = df.apply(lambda x: 1 if x[" Sentiment"] == " Positive" else 0, axis=1)

In [41]:
df

,Text,Sentiment,Source,Date/Time,User ID,Location,confidence_score,confidence
0,love product,Positive,Twitter,2023-06-15 09:23:14,@user123,New York,0.85,1
1,service terrible,Negative,Yelp Reviews,2023-06-15 11:45:32,user456,Los Angeles,0.65,0
2,movie amazing,Positive,IMDb,2023-06-15 14:10:22,moviefan789,London,0.92,1
3,im disappointed customer support,Negative,Online Forum,2023-06-15 17:35:11,forumuser1,Toronto,0.78,0
4,terribly disappointed service wouldnt go back bad,Negative,Product Feedback,2023-12-26 20:24:04,daenskawzp,New York,0.53,0
...,...,...,...,...,...,...,...,...
95,website confusing poorly designed,Negative,Website Review,2023-07-03 11:59:18,user789,Toronto,0.68,0
96,incredible experience theme park much fun,Positive,Trip Report,2023-07-03 14:40:05,thrillseeker1,Orlando,0.89,1
97,horrible experience would recommend anyone bad,Negative,Trip Report,2024-03-19 02:58:44,ecyscfhngd,New York,0.55,0
98,product quality bad completely unsatisfied bad,Negative,Product Feedback,2024-02-01 16:20:05,wsweeriejy,Toronto,0.59,0
99,unfriendly staff bad customer service bad,Negative,Trip Report,2024-02-03 22:59:22,lxpswqdlzj,New York,0.53,0

In [42]:
df.dropna(inplace=True)

In [43]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
import numpy as np

# Sample data
texts = df["Text"].tolist()

labels = df["confidence"].tolist() 

# Process texts
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.2, random_state=42)

# Train a model
model = LogisticRegression()
model.fit(X_train, y_train)

# Evaluate the model
print("LR Model accuracy:", model.score(X_test, y_test))

# Train a Random Forest model
model_rf = RandomForestClassifier()
model_rf.fit(X_train, y_train)

# Evaluate the Random Forest model
print("Random Forest model accuracy:", model_rf.score(X_test, y_test))

# Train a Support Vector Machines model
model_svc = SVC()
model_svc.fit(X_train, y_train)

# Evaluate the Support Vector Machines model
print("Support Vector Machines model accuracy:", model_svc.score(X_test, y_test))

# Train a Gradient Boosting model
model_gb = GradientBoostingClassifier()
model_gb.fit(X_train, y_train)

# Evaluate the Gradient Boosting model
print("Gradient Boosting model accuracy:", model_gb.score(X_test, y_test))

LR Model accuracy: 0.9
Random Forest model accuracy: 0.95
Support Vector Machines model accuracy: 0.9
Gradient Boosting model accuracy: 0.95

In [46]:
text = preprocess_text("he is a bad guy")
text_vectorized = vectorizer.transform([text])
x = model_gb.predict(text_vectorized)
print(x)
print("Predicted class:", x[0])

['he', 'is', 'a', 'bad', 'guy']
[0]
Predicted class: 0

In [1]:
import pickle

In [48]:
# Assuming your model is stored in a variable called `model`
with open('model_gb.pkl', 'wb') as file:
    pickle.dump(model_gb, file)